//1. functions
// i. String
let str1 = "Hi boy";
//a. length
// console.log(str1.length)

//b. index
// console.log(str1.indexOf("o"))
// function idx(str,elem){
//     let val
//     for(let i=0;i<str.length;i++){
//         if(elem==str[i]){
//             val = i
//         }
//     }
//     console.log(val)
// }
// idx(str1,"b")

//c. slice
// console.log(str1.slice(1,str1.length))
// function slc(str,start,end){
//     let slc1='';
//     for(let i=0;i<=str.length;i++){
//         if(i>=start && i<=end){
//             slc1 += str[i]
//         }
//     }
//     return slc1;
// }
// console.log(slc(str1,1,2))

// d.Sub strings
console.log(str1.substring(0,3));
// function sbtr(str, start, end) {
//   let slc1 = "";
//   for (let i = 0; i <= str.length; i++) {
//     if (i >= start && i <= end) {
//       slc1 += str[i];
//     }
//   }
//   return slc1;
// }
// console.log(slc(str1, 1, 2));

// 
